### ISSUE TITLE
[Feature request] Custom divider as widget

### ISSUE THREAD

**Issue by sirkalmi** [caduandrade/multi_split_view#16]
I want to set a widget as a divider, is it possible?

**Comment by caduandrade** [comment]
Hi!

It's not possible. It is only possible to define a custom painting. Are you needing to define your own widget?

**Comment by sirkalmi** [comment]
Hi!

"Are you needing to define your own widget?"

The graphic is designed with a unique divider that has a handle that looks like a floating button.

**Comment by caduandrade** [comment]
To hide, we can devise a method to set the weight or content of one of the sides to zero.

What are you thinking for the method that shows again? Are you keeping the oldest 2 weights and setting them again? Are you just setting the weight to .5?

**Comment by caduandrade** [comment]
I'll see how to make it available ok?

**Comment by sirkalmi** [comment]
I would be very grateful!

**Comment by caduandrade** [comment]
I think it might be necessary to have an optional builder to build each instance of Divider Widget. In this case, I think this could ignore the painter defined in the theme and use only the Widget. What do you think?

The Divider's thickness should continue to be defined by the theme. Then the created widget will be resized by that width or height.

**Comment by sirkalmi** [comment]
"I think it might be necessary to have an optional builder to build each instance of Divider Widget. In this case, I think this could ignore the painter defined in the theme and use only the Widget. What do you think?"

I think that would be the right solution.

**Comment by caduandrade** [comment]
Hi @sirkalmi !

If you want, you can try out the `master` branch before I release a version. Perhaps you will need something else.

```dart
    MultiSplitViewTheme(
        child: MultiSplitView(
            children: children,
            dividerBuilder: (Axis axis,
                int index,
                bool resizable,
                bool dragging,
                bool highlighted,
                MultiSplitViewThemeData themeData) {
              Color color = Colors.orange;
              if (dragging) {
                color = Colors.yellow;
              } else if (highlighted) {
                color = Colors.amber;
              }
              return Container(color: color);
            }),
        data: MultiSplitViewThemeData(dividerThickness: 20));
```

**Comment by caduandrade** [comment]
@sirkalmi 

I will release the version and close this issue. If you need anything, let me know.

**Comment by sirkalmi** [comment]
Yes, thank you very much for the development! Sorry for the late reply, I haven't had time to try yet.
