### ISSUE TITLE
Allow controller to programmatically resize

### ISSUE THREAD

**Issue by vipw** [caduandrade/multi_split_view#19]
I have a use case where the required size of a pane changes and I would like to reposition the divider programmatically.

Is there any way to do that?

**Comment by caduandrade** [comment]
Hi @vipw! I thought no one would notice... :wink: 

I'm going to change the `MultiSplitViewController` to allow setting the `weights`. The controller does not know the number of children. This will make it difficult but I'll see the best way to solve it.

**Comment by caduandrade** [comment]
@vipw, it's done (version 1.12.0).

Example:

```dart
controller.weights = [0.3, 0.7];
```

If you need anything else, let me know. If you can, like or star the project.

Thanks
