### ISSUE TITLE
Wrap content

### ISSUE THREAD

**Issue by ireshmw** [caduandrade/multi_split_view#2]
Hello!
**Is there any way to wrap the split view to its children's size?**
This is a nice Package, Thank you!

**Comment by caduandrade** [comment]
Hi @ireshmw !

Would you mind explaining better? Sorry, I didn't understand exactly what you meant by "wrap" in this case.

Did you think about a wrap class (https://api.flutter.dev/flutter/widgets/Wrap-class.html) style behavior?

Did you mean limit the size of the MultiSplitView? If so, I imagine that it may be possible to combine other Flutter Widgets.  MultiSplitView fits the size of the parent widget.

Tks!

**Comment by ireshmw** [comment]
https://user-images.githubusercontent.com/24836910/121221889-a6e23880-c8a3-11eb-94e3-072eeb9d55a2.mp4

Hello @caduandrade !

I created a CRUD widget that has a resizable columns table it has lazy loading and some kind of form builder, it's not perfect yet I'm working on this.  

inspired by [ vaadin CRUD UI ](https://vaadin.com/directory/component/crud-ui-add-on)

**I used your widget for resizable columns.** 

Best regards.
