### ISSUE TITLE
Feature Request: Allow divider to push other dividers

### ISSUE THREAD

**Issue by 0xNF** [caduandrade/multi_split_view#22]
For an example see codepen:
https://codepen.io/steve_walson/pen/oNprgre

It'd be really nice, as a user, to have the dividers be able to adjust the weights of panes in front and behind if the dragged divider pushes into other ones. It's hard to explain, but hopefully this gif makes it clear:

![DividerPush](https://user-images.githubusercontent.com/1915007/165462936-27794609-f7ef-4b43-8606-7364337543cf.gif)

**Comment by caduandrade** [comment]
Requires #22 and #24

**Comment by hieplee2997** [comment]
@caduandrade Is this feature available?

**Comment by caduandrade** [comment]
Will be resolved by #54

**Comment by caduandrade** [comment]
Better late than never (version 3.0.0) 😬
