### ISSUE TITLE
Divider color also sets the background color.

### ISSUE THREAD

**Issue by misha** [caduandrade/multi_split_view#3]
Per the issue title, if you use a transparent widget, the divider color appears as the background of the entire `MultiSplitView`

Very straightforward to reproduce, literally just use a `Text` as children.

**Comment by caduandrade** [comment]
Yes, you're right! I'll fix it.

**Comment by caduandrade** [comment]
@misha, it's done. If this package is helping you, don't forget to like it because it motivates me ;-).
