### ISSUE TITLE
How to get areas once weight has changed

### ISSUE THREAD

**Issue by martin-grannis** [caduandrade/multi_split_view#34]
Can you give an example of how I can get the new area sizes after a weight change?

I'd like to give users the chance to lock the split point after a resize, but can't find any way using onWeightChange to save the area info. I've got a controller in state but can't see it from onWeightChange function (unless I'm missing something obvious which is ever possible lol)

thanks
Martin

**Comment by martin-grannis** [comment]
turns out flutter was just optimising out "this" in my onWeightChanged function
Using  **this._controller.areas[0].weight** and saving that value works great for me
Doh !

**Comment by caduandrade** [comment]
Hi @martin-grannis! Sorry for the delay to reply. Glad it worked!
