### ISSUE TITLE
Allow tap gestures on the splitter

### ISSUE THREAD

**Issue by ykrasik** [caduandrade/multi_split_view#36]
Hi @caduandrade,

Thanks for this lib as well :)

I'd like to programatically change the position of the splitter when it is double clicked - reset it to its initial position. I couldn't find a way to detect any clicks on the splitter, am I missing something?

**Comment by caduandrade** [comment]
Hi @ykrasik! 

You are right, it's not possible. But your request is an order :stuck_out_tongue_winking_eye:

**Comment by caduandrade** [comment]
@ykrasik,

done :wink:

**Comment by ykrasik** [comment]
Thanks for the quick work! Will start playing with it.

**Comment by ykrasik** [comment]
Works great, thanks!
