### ISSUE TITLE
Consider exposing DividerWidget

### ISSUE THREAD

**Issue by klondikedragon** [caduandrade/multi_split_view#40]
I'm using MultiSplitView with a theme with one of the stock DividerPainter. However, I want to wrap the actual divider area widget with a tooltip widget. This could easily be accomplished by using the `dividerBuilder` property. Internally, if no custom dividerBuilder is set, it uses the `DividerWidget` and passes along the parameters from the function parameters of the dividerBuilder function, which will then use the painter in the theme to paint the divider based on its state. I want to continue using the painter framework (very convenient) but wrap the DividerWidget with a widget that will display a tooltip on hover. Right now DividerWidget is marked as internal so it's not exported.

**Comment by caduandrade** [comment]
I'll take a look okay? I only ask for a little time because I have demands on all my packages at the same time :smile:

**Comment by klondikedragon** [comment]
no worries, thanks for the fast response! I'd be happy to create a PR for this if you're OK with exposing the DividerWidget publicly with the package.
