### ISSUE TITLE
Maximum Weight and Maximum Size Support?

### ISSUE THREAD

**Issue by JohnF17** [caduandrade/multi_split_view#44]
Hello @caduandrade, I understand you are busy and I don't expect you to return a message back soon (🤞), just here to inquire about a potential support for maximum weight and maximum size.

P.S Awesome package

**Comment by caduandrade** [comment]
Thanks @JohnF17 !

I think it would be possible. Of course, the maximum of one area influences the other.

I'm creating a decision tree diagram to represent the already complex algorithm. I'm wanting to resolve all issues at once, first representing this diagram to make it easier.

**Comment by JohnF17** [comment]
That is wonderful news, can't wait for the next update. 

And might I just add, I was not expecting such a fast response, thank you for taking the time to consider this and responding as quick as you did 🙏

**Comment by ozkayas** [comment]
@JohnF17 
I am using the controller areas as follows and it works in version 2.2.0.
note: Looks like the latest version does not allow this usage.
`_horizontalController.areas = [Area(weight: 1), Area(minimalSize: 200)];`

**Comment by caduandrade** [comment]
Hi @ozkayas !

Hey! Sorry did not understand. I tested the minimal size in the new version and apparently, it's ok. But the weight is affected. As the second has a minimum size, the algorithm ignores the weight 1 of the first area. 

When the total weight is 1 and new areas are added, part of the weight of the old ones is redistributed.

I'm finishing the diagrams of the algorithms to make them easier to understand. Then I will complete with the new features.

How is it going:

![behavior](https://user-images.githubusercontent.com/8809484/232247488-7b379efd-4268-43ea-be64-9f4583ec8700.jpg)

**Comment by caduandrade** [comment]
Will be resolved by #54

**Comment by caduandrade** [comment]
Better late than never (version 3.0.0) :grimacing:
