### ISSUE TITLE
axis in dividerBuilder callback is always horizontal

### ISSUE THREAD

**Issue by cabbi** [caduandrade/multi_split_view#48]
Hi, I'm building a vertical split screen and wanted to draw a divider, but in the dividerBuilder callback  I get always axis parameter as Axis.horizontal

**Comment by caduandrade** [comment]
Hi @cabbi!

The API tricked you. In this case, it is the axis of the divider and not the screen. So in a vertical split screen, the divider will be horizontal. :wink:

**Comment by cabbi** [comment]
Got it thanks!
