### ISSUE TITLE
MultiSplitViewController should copy weights array

### ISSUE THREAD

**Issue by sgehrman** [caduandrade/multi_split_view#5]
I was passing in the weights, but it was a const [x,y,z].  When the controller tries to modify it, it fails.

I'm wrapping the MultiSplitView in another Widget that is a const widget, and the linter wants me to pass in a const [], so that's why I did that.

Work around for now is:
        MultiSplitViewController(weights: List<double>.from(widget.weights));

I recommend you turn on the the linter with all the strict settings and clean up the code to make sure it's solid.  I don't see that setup in the repo.  Maybe it will help.

**Comment by caduandrade** [comment]
Perfect!
I will do this after your PR from the other Issue ok? To avoid conflicts.
