### ISSUE TITLE
Multiple widgets used the same GlobalKey.

### ISSUE THREAD

**Issue by biancashouse** [caduandrade/multi_split_view#56]
I wonder if this rings any bells ?

**Comment by caduandrade** [comment]
Hi @biancashouse! 

Are you getting an error about `GlobalKey`? This package does not use `GlobalKey` ok? As the text says, you are probably keeping some `GlobalKey` in your `State` and reusing it in different `Widget`s. `GlobalKey` is unique per `Widget` as it is unique across the entire Flutter element tree.

Maybe you don't even need to use `GlobalKey`, ok? It's useful when you change the tree but need to maintain some state, for example.

**Comment by biancashouse** [comment]
Aha... I see: you use my widget's key in the Positioned Widget. I'm using GlobalKeys, so that's why I get this issue.

A workaround is for me to not use GlobalKeys as the _root_ widget in each split panel.
Would be nice if you could use your own key instead of borrowing mine ;-)

Anyway, nice pkg. Thanks.

[lib/src/multi_split_view.dart](https://github.com/caduandrade/multi_split_view/pull/26/files#diff-cfd68a369d512bcdc077b2ab088e0f6bf07455ea845bcec418634aefabeacc34)
Viewed
@@ -652,6 +652,7 @@ class _MultiSplitViewState extends State<MultiSplitView> {
      required Widget child,
      bool last = false}) {
    Positioned positioned = Positioned(
        key: child.key,
        top: _convert(distance.top, last),
        left: _convert(distance.left, last),
        right: _convert(distance.right, last),

**Comment by biancashouse** [comment]
I have created a devtools-like UI for editing flutter content. I definitely have to use GlobalKeys for every node in "my" widget tree so that user can select any widget by tapping it etc.

**Comment by caduandrade** [comment]
I understand. So I think it won't be a problem soon.
It won't be long before the new version is released. Maybe even today. In it, I no longer use `Positioned`/`Stack` ok?

**Comment by biancashouse** [comment]
Cool. Look fwd to downloading it. Much appreciated.

**Comment by biancashouse** [comment]
BTW - a quick workaround I'm using until the new version is that I simply wrap the views in a Builder.
