### ISSUE TITLE
How to adjust divider width for draggable areas

### ISSUE THREAD

**Issue by jochendev** [caduandrade/multi_split_view#57]
How to make the dividing line only occupy a small width between the two areas, but the actual draggable area is wider. What do I need to do?

**Comment by caduandrade** [comment]
Hi @jochendev!

You can change the divider thickness. 

```dart
MultiSplitViewTheme theme = MultiSplitViewTheme(
        child: multiSplitView,
        data: MultiSplitViewThemeData(dividerThickness: 5));
```
