### ISSUE TITLE
[Feacture] pass the MultiSplitViewController on onDividerDragUpdate

### ISSUE THREAD

**Issue by rodolfogoulart** [caduandrade/multi_split_view#71]
Can you add to onDividerDragUpdate the controller of the MultiSplitView?

I was using the previous version of the MultiSplitView, and used the onWeightChange to save the weight of the area, so the user when open the app will have the area started on their respective size as he changed before.

to replicate this on this new version its been hard, a lot of workaround to do.

if we can have like that

onDividerDragUpdate 

```dart
onDividerDragUpdate(index, controller){
}
```

to do that need to change this
```dart
typedef OnDividerDragUpdate = void Function(int index, MultiSplitViewController controller);
```
```dart
void _onDragUpdate(
      DragUpdateDetails detail, int index, ControllerHelper controllerHelper) {
    if (_draggingDivider == null) {
      return;
    }

    final Offset offset = _offset(context, detail.globalPosition);
    final double position;
    if (widget.axis == Axis.horizontal) {
      if (detail.delta.dx == 0) {
        return;
      }
      position = offset.dx;
    } else {
      if (detail.delta.dy == 0) {
        return;
      }
      position = offset.dy;
    }

    final double newDividerStart = position - _draggingDivider!.initialInnerPos;
    final double lastDividerStart = _layoutConstraints.dividerStartOf(
        index: index,
        controller: _controller,
        antiAliasingWorkaround: widget.antiAliasingWorkaround);

    DividerUtil.move(
        controller: _controller,
        layoutConstraints: _layoutConstraints,
        dividerIndex: index,
        pixels: newDividerStart - lastDividerStart,
        pushDividers: widget.pushDividers);

    controllerHelper.notifyListeners();
    if (widget.onDividerDragUpdate != null) {
      //TODO: Change here
      Future.delayed(Duration.zero, () => widget.onDividerDragUpdate!(index, _controller));
    }
  }
```

this way, i can have acess to the area itself,

**Comment by caduandrade** [comment]
Hi @rodolfogoulart!

Of course, but just curious, you are using `MultiSplitView` inside a `StatelessWidget` right? Is that why you don't have the reference for the `MultiSplitViewController`?

**Comment by caduandrade** [comment]
I asked because with the state you already have the reference to the controller:

```dart
class MultiSplitViewExampleState extends State<MultiSplitViewExample> {
  final MultiSplitViewController _controller = MultiSplitViewController();

  @override
  void initState() {
    super.initState();
    _controller.areas = [
      Area(builder: (c, a) => const MyStatefulWidget()),
      Area(builder: (c, a) => const MyStatefulWidget())
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Multi Split View Example')),
        body: MultiSplitView(
            controller: _controller,
            onDividerDragUpdate: _onDividerDragUpdate));
  }

  void _onDividerDragUpdate(int index) {
    // _controller.areas
  }
}
```

**Comment by rodolfogoulart** [comment]
Obrigado @caduandrade . Com esta nova versão eu estava com problemas para entender as modificações que precisava fazer aqui. Mas fiz as modificações criando o controller do MultiSplitViewController no initState e usando o builder: (BuildContext context, Area area) do MultiSplitView, _no começo não tinha entendido aquele builder não_ kkkkk

mas ficou bacana, bom que a nova versão eliminou um bug que estava sofrendo aqui, na antiga versão.


Outra coisa, nesta nova versão, se puder mesmo disponibilizar o controller no onDragUpdate e nos outros métodos que somente esta passando o index, iria ajudar aqueles que por algum motivo estejam usando o **initialAreas**, porque quando usado sem o controller, os métodos (onDividerDragUpdate, onDividerDoubleTap, onDividerTap) ficam meio sem sentido, só sabendo o index, sem as funções do controller interno. mas fica mais para sugestão do que para necessidade rs

**Comment by stan-at-work** [comment]
For the peaple that don't speak: Portuguese...


> Thank you caduandrade. With this new version, I was having trouble understanding the modifications I needed to make here. But I made the changes by creating the MultiSplitViewController controller in the initState and using the builder: (BuildContext context, Area area) of MultiSplitView. At first, I didn’t understand that builder at all hahaha.
> 
> But it turned out great. It's good that the new version eliminated a bug that I was experiencing here in the old version.
> 
> Another thing, in this new version, if you could make the controller available in onDragUpdate and other methods that are currently only passing the index, it would help those who, for some reason, are using initialAreas. Because when used without the controller, the methods (onDividerDragUpdate, onDividerDoubleTap, onDividerTap) don't make much sense, only knowing the index without the functions of the internal controller. But this is more of a suggestion than a necessity haha.

**Comment by caduandrade** [comment]
Oi @rodolfogoulart! Estou fechando a issue ok? Eu estou mantendo os métodos sem receber o controlador por parâmetro para tentar ficar menos "verbose" e no padrão do Flutter ok? Imagino que seja estilo `TextField`. Ele também cria automaticamente um controlador interno mas se você precisar utilizá-lo, é necessário usar dentro de um `StatefulWidget`.

Abraços!
