### ISSUE TITLE
The divider does not move when the widget's size includes a tiny fractional value.

### ISSUE THREAD

**Issue by caduandrade** [caduandrade/multi_split_view#78]
This small fraction causes floating point to generate inappropriate subtraction. This results in incorrect behavior in `LayoutConstraints.adjustAreas`.

It was detected on Windows but it is possible to simulate with:

```dart
Padding(
          padding: const EdgeInsets.fromLTRB(0.000000001,16,16,16),
          child: MultiSplitViewTheme(
              data: MultiSplitViewThemeData(
                  dividerPainter: DividerPainters.grooved2()),
              child: multiSplitView))
```

**Comment by caduandrade** [comment]
Version 3.2.2 released

**Comment by lorenzogiarola** [comment]
Hi, i'm still encountering this bug, but I manage to solve it using the multi split view widget inside a sized box, where i set height and width to their max values, floored to double. I also have to round to double each area size in the multi split view controller.
