### ISSUE TITLE
How to set an area size on `onDividerDoubleTap`?

### ISSUE THREAD

**Issue by stephane-archer** [caduandrade/multi_split_view#79]
How to set an area size on `onDividerDoubleTap`?
```
class MyHomePage extends StatelessWidget {
  final _multiSplitViewController = MultiSplitViewController(
    areas: [
      Area(
        flex: 0.5,
        builder: (context, area) {
          return const MyNavigationRail();
        },
      ),
      Area(
        builder: (context, area) {
          return const MainUI();
        },
      )
    ],
  );

  MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: MultiSplitViewTheme(
        data: MultiSplitViewThemeData(
            dividerThickness: 8,
            dividerPainter: DividerPainters.grooved1(
                backgroundColor: const Color.fromRGBO(73, 73, 73, 1),
                color: const Color.fromARGB(255, 42, 42, 42),
                highlightedColor: const Color.fromRGBO(33, 33, 33, 1))),
        child: MultiSplitView(
          controller: _multiSplitViewController,
          onDividerDoubleTap: (dividerIndex) {
            _multiSplitViewController.getArea(0).size = 0; // no setter
            _multiSplitViewController.getArea(0).flex = 0; // no setter
          },
        ),
      ),
    );
  }
}
```

**Comment by stephane-archer** [comment]
I want to control the divider position on `onDividerDoubleTap`

**Comment by stephane-archer** [comment]
here is my current solution:
```
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _multiSplitViewController = MultiSplitViewController(
    areas: [
      Area(
        flex: 0.5,
        builder: (context, area) {
          return const MyNavigationRail();
        },
      ),
      Area(
        builder: (context, area) {
          return const MainUI();
        },
      )
    ],
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: MultiSplitViewTheme(
        data: MultiSplitViewThemeData(
            dividerThickness: 8,
            dividerPainter: DividerPainters.grooved1(
                backgroundColor: const Color.fromRGBO(73, 73, 73, 1),
                color: const Color.fromARGB(255, 42, 42, 42),
                highlightedColor: const Color.fromRGBO(33, 33, 33, 1))),
        child: MultiSplitView(
          controller: _multiSplitViewController,
          onDividerDoubleTap: (dividerIndex) {
            setState(() {
              _multiSplitViewController = MultiSplitViewController(
                areas: [
                  Area(
                    flex: 0,
                    builder: (context, area) {
                      return const MyNavigationRail();
                    },
                  ),
                  Area(
                    builder: (context, area) {
                      return const MainUI();
                    },
                  )
                ],
              );
            });
          },
        ),
      ),
    );
  }
}

```
it's ugly but it works for now
I hope we can improve the situation

**Comment by caduandrade** [comment]
Hi @stephane-archer!

Currently, to change the value of an area it is necessary to recreate the entire layout like any other layout. It would also not be possible to change the flex of just one area since this influences the neighboring area (when one stretches, another needs to shrink). I believe that setting the flex value directly in a single area would not be sufficient for the API. Perhaps what could exist is a method to only set the values ​​of all areas at the same time without changing their Widgets.

**Comment by stephane-archer** [comment]
@caduandrade, Can you clarify what is the issue with resizing an existing area (in that case this would be resizing 2 areas, one bigger and one smaller)? can you just change the constraints and then call the build function of the child widget?

**Comment by stephane-archer** [comment]
@caduandrade these a great ways to simplify my code, thank you.
I will update my code now!

Do you think we can improve MultiSplitView API to avoid recreating areas?
`onDividerDoubleTap` gives us a `dividerIndex` Would you be able to add something to get from a `dividerIndex` a position and a possibility to change this position?

**Comment by caduandrade** [comment]
I think it's not impossible. But needs to be as intuitive as possible as you will also need to change the `size`, `max` and `min` values. It will never be perfect :smile: .

**Comment by stephane-archer** [comment]
@caduandrade What I don't understand is that with my mouse I'm able to resize each panel without any complexity, what makes it impossible with an API?
When I double tap on a divider, I want to click on this divider and push it as much as possible to the left.
If I do it myself with my mouse it would be easy.
What I'm missing?

**Comment by caduandrade** [comment]
Hi @stephane-archer!

Short version: Yes, it would be possible, but not with the current API. Needs a new method. The current one is made for the drag event with/without pushing option and works only with pixels.

Large version: :open_mouth:

Drag uses `DividerUtil`'s protected `_resizeAreas` and `move` methods. The `move` is just an entry point for `_resizeAreas`.

```dart
static double move(
      {required MultiSplitViewController controller,
      required LayoutConstraints layoutConstraints,
      required int dividerIndex,
      required double pixels,
      required bool pushDividers}) {
```

```dart
static double _resizeAreas(
      {required double pixelsToMove,
      required int direction,
      required MultiSplitViewController controller,
      required LayoutConstraints layoutConstraints,
      required int shrinkAreaIndex,
      required int growAreaIndex,
      required bool pushDividers}) {
```

It only works with pixels and internally knows how to convert to flex when necessary. This is the first problem in your case, there is nothing to directly change the `flex`. In the current implementation, when you completely shrink a `flex` area 1, its value is transferred to the neighboring `flex` area. So `[1][1]` turns into `[0][2]`. This is the second point, to adjust an area, it is currently necessary to adjust the neighboring area at the same time. In your most basic case with 2 areas, it would make no difference `[1][1]` to become `[0][1]` (changing only one area directly) or to `[0][2]` (via the drag event). The final effect on the screen would be `[0%][100%]`. But this is not true when there are other flex areas. For example, `[1][1][2]` represents `[25%][25%][50%]`. Shrinking the first via drag `[0][2][2]`, the user would see `[0%][50%][50%]`. But if you only reset the size of the first `[0][1][2]`, the last one will deform and the screen will have the proportion `[0%][33.33%][66.66%]`. This transfer of value to the neighbor also occurs with pixels. It would not be possible to reset pixels in one area and not change the neighboring area as this would result in inconsistency resolution when the total number of pixels is smaller than the size of the component.

I don't see a problem with there being a method to make it easier to change just one area and generate a different visual effect than the current drag. It is acceptable and expected. But what I wanted to say is that there is nothing ready and easy to expose this feature.

Conclusion, finally, :laughing: : It is in my plans to review this along with the possibility of having pixel + min/max in flex or flex + min/max in pixels. Different uses generate more complexity.

**Comment by caduandrade** [comment]
I created the issues: 

- #80
- #81

**Comment by stephane-archer** [comment]
@caduandrade I would like to thank you for all your help and explanation, and I would like to thank you for considering my needs and the willingness to improve the API/Library
