### ISSUE TITLE
Allow changing the size, min and max of just one area.

### ISSUE THREAD

**Issue by caduandrade** [caduandrade/multi_split_view#81]

**Comment by JulienElkaim** [comment]
Hello Caduandrade, thank you for this great package!

Is it still on the roadmap? Saw on #35 that this will allow for Animation as well. Would be awesome to animate the resizing of an Area !

Best, Julien

**Comment by caduandrade** [comment]
Sure @JulienElkaim! But sorry because I'm short on time. I'm coding Flutter when I have free time or on weekends.

**Comment by caduandrade** [comment]
@JulienElkaim , I took a look now. I think I have an idea of ​​how to implement this. It's not as simple as it sounds but it looks promising. I'll make some adjustments first.

**Comment by caduandrade** [comment]
`Area` will need to be a `ChangeNotifier`.

**Comment by caduandrade** [comment]
The `Area` cannot have both a null `flex` and a null `size` value at the same time. Therefore, it will not be possible to transform a `flex` area into a `size` area or vice versa using:

```dart
// area flex is not null
area.flex = null;
area.size = 100;
```

or

```dart
// area size is not null
area.size = null;
area.flex = 2;
```

**Comment by caduandrade** [comment]
Since dragging a divider only transfers the value from one area to another, the total flex sum may increase by changing the value of a single area. It is up to the developer to keep the logic that makes sense.

Example:
1. 2 areas instantiated. Result: each with flex value 1.
2. The user completely shrinks the first area. Result: first area with flex 0 and second area with flex 2. The sum of flex is 2.
3. Flex value of the first area is programmatically changed to 2. Result: first area with flex 2 and second area with flex 2. The sum of flex is 4.

**Comment by caduandrade** [comment]
When the dev programmatically changes the size/flex of an area and generates an inconsistency, the layout needs to automatically adjust given the inconsistency handling settings.

**Comment by caduandrade** [comment]
It's done. Version 3.6.0 released. Thanks.

**Comment by JulienElkaim** [comment]
Thank you @caduandrade !!

In your exemple, do you mean the sum moving from 2 to 4 is inconsistent and will break the mechanism?

If yes, can we "normalise" the value? flex value is a double so:

i.e if the initial sum was 2, and new sum is 5, the factor change is 5/2. So we divide each new value of the areas by 5/2, and the final new sum is 2, with the new proportions for each areas.

Let me know if it was the issue or not at all

**Comment by caduandrade** [comment]
Hi @JulienElkaim! 

The 2/4 example is not inconsistent, okay? It's just a concern that the developer needs to have. This is similar to what would happen if he changed only one flex widget within the Row Flutter Widget.

An example of inconsistency is programmatically setting all Areas to flex 0. In this case, the handler will change the value of all areas to 1.
