### ISSUE TITLE
A mode without a dividerPainter

### ISSUE THREAD

**Issue by sjustfly** [caduandrade/multi_split_view#83]
<img width="795" alt="image" src="https://github.com/user-attachments/assets/2b7f31d4-9cc5-4ee5-b46c-ab4682e9c4fc">

Is it possible to provide a mode without a dividerPainter, but still draggable, like in Android Studio? I think this is a feature that everyone wants, as most apps are designed this way.

**Comment by caduandrade** [comment]
@sjustfly,

The feature will be like this:

```dart
MultiSplitViewTheme(
              data: MultiSplitViewThemeData(
                dividerThickness: 0,
                  dividerHandleBuffer: 5),
              child: multiSplitView)
```

You need to remove the divider thickness but use a buffer around it. 5 on each side. The total drag area will be 10.

**Comment by caduandrade** [comment]
@sjustfly

Version 3.3.0 released
