### ISSUE TITLE
Add onDividerDragStart and onDividerDragEnd

### ISSUE THREAD

**Issue by The4Summers** [caduandrade/multi_split_view#86]
Would be nice if you could add the ability to configure callback methods for "onDividerDragStart" and "onDividerDragEnd".
I have a case where I just want to keep in memory that last size (flex) of my panels after a divider drag has been performed. For the moment I update these values in "onDividerDragUpdate", which is good but a "onDividerDragEnd" would have been good enough and more efficient.

**Comment by proteye** [comment]
@The4Summers Hello. I've added this functionality to a new package created from this.
https://pub.dev/packages/multi_split_view_next

**Comment by caduandrade** [comment]
Thanks, @The4Summers, it will be available in version 3.3.0.
