### ISSUE TITLE
We should be able to configure a "grabber zone" larger than the divider

### ISSUE THREAD

**Issue by The4Summers** [caduandrade/multi_split_view#87]
Sometime we want to draw a very thin divider without gaps on each side, but the problem with such thin divider is that the grab zone is also very thin! 
It would be nice to be able to configure a grabber zone larger than the divider itself.

**Comment by proteye** [comment]
@The4Summers Hello. I've added grabber zone to a new package created from this.
https://pub.dev/packages/multi_split_view_next

**Comment by caduandrade** [comment]
@The4Summers , good idea. Thanks. I'll do it.

**Comment by caduandrade** [comment]
It will be resolved by #83

**Comment by caduandrade** [comment]
@The4Summers , I'm not sure if it makes sense to allow it to be smaller than the thickness of the divider. :thinking:

**Comment by caduandrade** [comment]
@The4Summers

This will add a buffer around the current `dividerThickness`.

```dart
MultiSplitViewTheme(
              data: MultiSplitViewThemeData(
                  dividerHandleBuffer: 5,
                  dividerPainter: DividerPainters.grooved2()),
              child: multiSplitView)
```

The default `dividerThickness` is 10. So, the total drag area will be 20 (10 + 5 on each side).

**Comment by caduandrade** [comment]
@The4Summers 

Version 3.3.0 released
