### ISSUE TITLE
Error Encoding Area Object to JSON

### ISSUE THREAD

**Issue by stan-at-work** [caduandrade/multi_split_view#94]
### Description

When attempting to encode an `Area` object to JSON, the following error message is encountered:

```
Error: Converting object to an encodable object failed: Instance of '_AreaId'
```

### Steps to Reproduce

1. Create an `Area` object.
2. Attempt to encode the `Area` object to JSON using your chosen JSON encoding method.
3. Observe the error message.

### Expected Behavior

The `Area` object should be successfully encoded to JSON without errors.

### Actual Behavior

The encoding process fails with the error message: 
```
Error: Converting object to an encodable object failed: Instance of '_AreaId'
```

To solve this, we should make _AreaId serializable:

```dart
import 'package:flutter/material.dart';
import "dart:convert";

void main() {
  final uniqueKey = _AreaId();

  print(jsonEncode(uniqueKey));
}

class _AreaId {
  _AreaId({String? id}) : id = id ?? UniqueKey().hashCode.toString();

  final String id;

  @override
  String toString() {
    return 'area id: $id';
  }

  _AreaId fromJson(Map<String, dynamic> json) {
    return _AreaId(
      id: json['id'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
    };
  }

  @override
  bool operator ==(Object other) {
    return other is _AreaId && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}


```

**Comment by stan-at-work** [comment]
@caduandrade I can make a pr is you wan that

**Comment by caduandrade** [comment]
Sure @stan-at-work. Thanks!

**Comment by caduandrade** [comment]
@stan-at-work, is it necessary to generate a dependency on the uuid package?

**Comment by stan-at-work** [comment]
> @stan-at-work, is it necessary to generate a dependency on the uuid package?

Not really, its also possible with a UniqueKey...

**Comment by stan-at-work** [comment]
> > @stan-at-work, is it necessary to generate a dependency on the uuid package?
> 
> Not really, its also possible with a UniqueKey...

I will create a new PR using UniqueKeys instead of UUIDs then...

**Comment by stan-at-work** [comment]
@caduandrade 

Here it is: https://github.com/caduandrade/multi_split_view/pull/95
